export default {
  site: {
    name: "Blyss",
    baseUrl: "https://example.com",
    defaultLanguage: "en",
    publisher: {
      type: "Organization",
      name: "Blooniverse",
      url: "https://example.com"
    },
    languages: {
      en: {
        label: "English",
        locale: "en",
        description: "A lean Markdown-powered website.",
        labels: {
          mainNavigation: "Main navigation",
          home: "Home",
          about: "About",
          language: "Language",
          generatedBy: "Generated by Blyss"
        }
      },
      de: {
        label: "Deutsch",
        locale: "de-CH",
        description: "Eine schlanke, Markdown-basierte Website.",
        labels: {
          mainNavigation: "Hauptnavigation",
          home: "Startseite",
          about: "Über Blyss",
          language: "Sprache",
          generatedBy: "Generiert von Blyss"
        }
      }
    }
  },
  directories: {
    content: "content",
    public: "public",
    static: "static",
    templates: "src/templates"
  },
  build: { cleanUrls: true },
  server: { fallbackPort: 3000 }
};
